language: java
sudo: false
script: mvn test jacoco:report coveralls:report
jdk:
- oraclejdk7
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
    secure: JIObGWMPCNPWMT6vGJzjS7cfbwLsbNuK+TLigRUD2dbYrNgg6sC7SESEL5ZxXOdF8Tr9eyryhVDnzU1YkrL2FX1P5xPx++5AGqGR0gmsK5o5qFTReIQOVDvvb31N60VTQJUHEVgx1Y3N71MvtxPVTLAft8dhU22ft7b3/tKHO6j0Pyt3ki32grGWct/RdTr9UuO5M0nN+BqATe0WFO7nIEKVgEgZglI6RrSOUfz1EI07R+8C0UDUACtbIGuRoOYf7AOy6hiQdvwbGj85cR3Ul+dEBb/6te+xZbV1hn6V8zOfWyswk9rNToNpJnsD1dR3WwmECUY54LGZncW4z9mcdvz94llAsWFBX6cKgAxujR9rLMNOPHfrdwlYWc6bjtgq+VZw6WAVZrTtZhMycxWYKdHSUuUqKLBlRfZRKgCP3sGLlU+GI2QCVks6Tm03O6ZHJ1O2D7SWZlJ09NVeiPv61PRi5hSUa05D/yoqeTvyHcXNgCpJnjddgMyC0mux+ICDmLUo43S3ty6rIcQAze4BUKr8wQsxBXye+FKXusORkiuX6a1AGa3GDR3atSxnPbyBBAhuQRZSa6DVaeixXIQeTHKuiKlCUB/bjXR9pB6Dv/8D0nt8dahlKIzDkmPmF8m2hnRemD+oAOlv6YBsBazf4cJvRgfYQoWft/2PGUbsFIo=
after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && { mvn deploy --settings .travis-settings.xml
  -DskipTests=true -B; };'
