language: java
sudo: false
script: mvn test jacoco:report coveralls:report
jdk:
- oraclejdk7
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - GITHUB_LOGIN=tdurieux
  - secure: fQi+jZ/1lPpGvmrlAVIY9A8AN8iQBn/ZbvjfT39qB8Ey4Y9sIwuwHVtCnh5f3QPgYWInHCzgu/VS6IZZmhbXpVAzI3m7n2YnCi6dy6vDS6btLxGRCtRX9CWFD31tEJdvSzSMtgDjOqkt9rkvHZ9En8O9WCRomKYsYKu2cnZdxobPLABoW5LVLxrLQwTz3ZtJIQe3DH1HIFV4qNAKRZO3/osT9oCG/Xvw6gJtY1WqxIfQ1QPkNFQHNTSRgHIRMuT0K62erDRUnwZMAOWCXrbykxxjVgN8kQnCZdw7jXnk2RkHbS8CoK6AbxMs4vxr4IrddhjgDWEIruIUK+tY01blcKl0SGOgnP/UqLKcUU0ORWU0uF6R1snHdTdl2JnBtU9j26dUat2OPaKcLKQekXyWDNUQpObuluwnqYE0k8gXC4m6aHsW8640bvNXBuzA6THTk3VSJtMWKZsBQCzklyr9Lia2x1KP/r6RGt8bhhZdgqWQ3XG6PW1q8bHdKLBDqcrOFOdFcOuuEna4BB1S7//TL/ZL7McdfPAX3nXmRFJJxnRmIbircLRaDCc7Vxsf4VJGyLNbuIEHq0hKmUH1UnT29R/p+tggJMxu8mNIU1Ito6khdsb9/vLsrRP0ESuV5o06fOSBhTnwTv++zqPuTsBP25XMvgfzGFnhiT19QdNt44A=
after_success:
- "[[ $TRAVIS_BRANCH == \"master\" ]] && { mvn deploy --settings .travis-settings.xml -DskipTests=true -B; };"
