language: java
sudo: false
script: mvn test jacoco:report coveralls:report
jdk:
- openjdk8
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && [[ $TRAVIS_JDK_VERSION == "openjdk8" ]] &&
  { mvn deploy --settings .travis-settings.xml -DskipTests=true -B; };'
env:
  global:
    secure: R/gJYV4I6O3Fl14cRzSg25C6eBQuVIb49nVnhou5Mxroz5Xta/Nkb+ylO8Yly13xxrL0IEhPjlZTUJsa/lbIpmMj1ztCJ4iJP0brhy6AU3xRrMXUykztECORoBYPOyFBEst/FGhgDYl3sUYzZ03hQfKaeNxnN95Yf2IDIW4/xZAa235jl4cSW/Lcs+k7affuGFc+/XOuxm+yBybbL67oiCMCOcovIMXFtg1FpclrkUag+A9+dZ2l35LOPOwUJH2zXZj2VYNNW4NclxLAPoJQKfR1xNkkRJmoeWqYohB+8/4dqWahxVoLK4taBF672Vn7mRZy+wmmY3dIsuu1aZvdfnUb9nd9MV6R7d1alFZvI2ckLO+/nXrLkhxs4R1l+1pH/3Iz9HVfjqHolD3hVnBJEDhx6ZE20PDBMURlUa52IOoExV4RWGWgMDm5MTao0dILRbE8NX79uIcUc9pGAwaLN/HbNaky4FkLYN97kTmxB53VoQLnbeLczCOQ0YLfE+yw/EDOEFhzg+DTutHM1JlH/mivv3s/EX99vbdIkAftNiYh3DOf6hZGgswYbBTwThGETVrTMm/9UfeNrinfDZE+CJMS1hxsET2jY62uWLk5jF7JhinjQA/N0qpVUrv8EgPQqENxyIlETSZ9qhrlscvweJDNVHTIIz23im99KSk4Xjc=
